'use strict';
const app=document.querySelector('#app');let catalog;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=v=>{try{const u=new URL(v,location.href);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:''}catch{return ''}};
const date=v=>v?new Date(v+'T00:00:00').toLocaleDateString('ru-RU'):'';
const latest=m=>m.versions[0];
function validate(c){if(c.schemaVersion!==1||!Array.isArray(c.mods))throw Error('Неверный формат каталога');const ids=new Set();for(const m of c.mods){if(!/^[a-z0-9-]+$/.test(m.id)||ids.has(m.id)||!m.name||!Array.isArray(m.versions)||!Array.isArray(m.screenshots))throw Error('Проверьте идентификаторы, названия и версии');ids.add(m.id);for(const v of m.versions){if(!v.version||!/^\d{4}-\d{2}-\d{2}$/.test(v.date)||!Array.isArray(v.links))throw Error('Проверьте данные версии');for(const l of v.links)if(!l.label||!/^https:\/\//.test(l.url)||!url(l.url))throw Error('Для скачивания нужны ссылки HTTPS');}}return c;}
function cover(m){return `<div class="cover">${m.cover&&url(m.cover)?`<img src="${esc(url(m.cover))}" alt="" loading="lazy">`:`<span class="cover-title">${esc(m.name)}</span>`}</div>`}
function renderCatalog(){app.innerHTML=`<div class="intro"><div><span class="eyebrow">FARMING SIMULATOR</span><p class="muted">Авторские моды BMP. Описания, обновления и ссылки на скачивание.</p></div><span class="count">Модов в каталоге: ${catalog.mods.filter(m=>m.published).length}</span></div><div class="tools"><input id="search" type="search" placeholder="Найти мод…" aria-label="Поиск модов"><select id="game" aria-label="Игра"><option value="">Все игры</option>${[...new Set(catalog.mods.filter(m=>m.published).map(m=>m.game))].map(g=>`<option>${esc(g)}</option>`).join('')}</select><select id="category" aria-label="Категория"><option value="">Все категории</option>${[...new Set(catalog.mods.filter(m=>m.published).map(m=>m.category))].map(c=>`<option>${esc(c)}</option>`).join('')}</select><select id="sort" aria-label="Сортировка"><option value="date">Сначала обновлённые</option><option value="name">По названию</option></select></div><div id="cards" class="grid"></div>`;const draw=()=>{const q=document.querySelector('#search').value.toLocaleLowerCase(),cat=document.querySelector('#category').value,game=document.querySelector('#game').value;const mods=catalog.mods.filter(m=>m.published&&(!game||m.game===game)&&(!cat||m.category===cat)&&(m.name+' '+m.summary).toLocaleLowerCase().includes(q)).sort((a,b)=>document.querySelector('#sort').value==='name'?a.name.localeCompare(b.name,'ru'):(latest(b)?.date??'').localeCompare(latest(a)?.date??''));document.querySelector('#cards').innerHTML=mods.map(m=>`<a class="card" href="#mod/${esc(m.id)}">${cover(m)}<div class="card-body"><span class="tag">${esc(m.game)} · ${esc(m.category)}</span><h2>${esc(m.name)}</h2><p>${esc(m.summary)}</p><div class="card-bottom"><span>${latest(m)?'v'+esc(latest(m).version):'<span class="demo">Пример карточки</span>'}</span><span class="muted">${latest(m)?date(latest(m).date):'Подробнее'}</span></div></div></a>`).join('')||'<p class="empty">Ничего не найдено. Попробуйте другой запрос.</p>';};for(const id of ['search','game','category','sort'])document.getElementById(id).addEventListener('input',draw);draw();}
const links=v=>(v?.links??[]).map(l=>`<a class="btn" href="${esc(url(l.url))}" target="_blank" rel="noopener noreferrer">Скачать · ${esc(l.label)}</a>`).join('');
function detail(id){const m=catalog.mods.find(m=>m.id===id&&m.published);if(!m){app.innerHTML='<h1>Мод не найден</h1><a href="#">Вернуться к каталогу</a>';return}app.innerHTML=`<a class="back" href="#">Вернуться к каталогу</a><div class="detail"><section><p class="eyebrow">${esc(m.game)} · ${esc(m.category)}</p><h1>${esc(m.name)}</h1>${m.demo?'<p class="notice">Пример карточки. Версии и ссылки ещё не опубликованы.</p>':''}<p class="description">${esc(m.description)}</p>${m.credits?.length?`<p class="muted">Авторы: ${m.credits.map(esc).join(', ')}</p>`:''}<div class="gallery">${m.screenshots.filter(url).map(s=>`<a href="${esc(url(s))}" target="_blank" rel="noopener"><img src="${esc(url(s))}" alt="Скриншот ${esc(m.name)}" loading="lazy"></a>`).join('')}</div><h2>История версий</h2>${m.versions.map(v=>`<article class="version"><h3>Версия ${esc(v.version)}</h3><small>${date(v.date)}</small><p>${esc(v.changes)}</p><div class="actions">${links(v)}</div></article>`).join('')||'<p class="muted">Опубликованных версий пока нет.</p>'}</section><aside class="box"><span class="tag">${esc(m.game)}</span><h2>${latest(m)?'Версия '+esc(latest(m).version):'Скоро здесь'}</h2><p class="muted">${latest(m)?'Обновлено '+date(latest(m).date):'Ссылка появится после публикации версии.'}</p><div class="actions">${links(latest(m))}</div><small>Способ установки и требования смотрите в описании. Игровые моды обычно устанавливаются в папку mods; утилиты и шаблоны используются отдельно.</small>${m.sourceUrl?`<div class="actions"><a class="btn secondary" href="${esc(url(m.sourceUrl))}" target="_blank" rel="noopener noreferrer">Страница на KingMods</a></div>`:''}</aside></div>`;}
function updates(){const entries=catalog.mods.filter(m=>m.published).flatMap(m=>m.versions.map(v=>({m,v}))).sort((a,b)=>b.v.date.localeCompare(a.v.date));app.innerHTML='<span class="eyebrow">ЖУРНАЛ</span><h1>Обновления модов</h1>'+ (entries.map(({m,v})=>`<article class="version"><span class="tag">${date(v.date)}</span><h2><a href="#mod/${esc(m.id)}">${esc(m.name)} · ${esc(v.version)}</a></h2><p>${esc(v.changes)}</p></article>`).join('')||'<p class="empty">Здесь появятся новые версии модов.</p>');}
function route(){const h=location.hash;document.querySelectorAll('[data-nav]').forEach(a=>a.setAttribute('aria-current',(h==='#updates'&&a.dataset.nav==='updates'||(!h||h==='#')&&a.dataset.nav==='catalog')?'page':'false'));if(h==='#updates')updates();else if(h.startsWith('#mod/'))detail(h.slice(5));else renderCatalog();window.scrollTo(0,0);}
fetch('data/catalog.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('Не удалось загрузить каталог');return r.json()}).then(c=>{catalog=validate(c);route();window.addEventListener('hashchange',route)}).catch(e=>{app.innerHTML=`<h1>Каталог недоступен</h1><p>${esc(e.message)}</p><button class="btn" onclick="location.reload()">Повторить</button>`});
