'use strict';
const app=document.querySelector('#app');let catalog;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=v=>{try{const u=new URL(v,location.href);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:''}catch{return ''}};
const date=v=>v?new Date(v+'T00:00:00').toLocaleDateString('ru-RU'):'';
const latest=m=>m.versions[0];
function validate(c){if(c.schemaVersion!==1||!Array.isArray(c.mods))throw Error('Неверный формат каталога');const ids=new Set();for(const m of c.mods){if(!/^[a-z0-9-]+$/.test(m.id)||ids.has(m.id)||!m.name||!Array.isArray(m.versions)||!Array.isArray(m.screenshots))throw Error('Проверьте идентификаторы, названия и версии');ids.add(m.id);for(const v of m.versions){if(!v.version||!/^\d{4}-\d{2}-\d{2}$/.test(v.date)||!Array.isArray(v.links))throw Error('Проверьте данные версии');for(const l of v.links)if(!l.label||!/^https:\/\//.test(l.url)||!url(l.url))throw Error('Для скачивания нужны ссылки HTTPS');}}return c;}
function cover(m){return `<div class="cover">${m.cover&&url(m.cover)?`<img src="${esc(url(m.cover))}" alt="" loading="lazy">`:`<span class="cover-title">${esc(m.name)}</span>`}</div>`}
function downloadLink(m){const available=(latest(m)?.links??[]).filter(l=>url(l.url));return available.find(l=>{try{return /(^|\.)modsfire\.com$/i.test(new URL(l.url).hostname)}catch{return false}})??available[0];}
function quickDownload(m){const link=downloadLink(m);return link?`<div class="card-download"><a class="btn" href="${esc(url(link.url))}" target="_blank" rel="noopener noreferrer" aria-label="Скачать ${esc(m.name)} — версия ${esc(latest(m).version)}">Скачать</a><button class="share-button" type="button" data-copy-url="${esc(url(link.url))}" aria-label="Поделиться ссылкой на последнюю версию ${esc(m.name)}" title="Скопировать ссылку на последнюю версию"><svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.5 6.8-4M8.6 13.5l6.8 4"/></svg></button></div>`:'<div class="card-download"><span class="muted">Ссылка пока недоступна</span></div>';}
function renderCatalog(){app.innerHTML=`<div class="tools"><input id="search" type="search" placeholder="Найти мод…" aria-label="Поиск модов"><select id="game" aria-label="Игра"><option value="">Все игры</option>${[...new Set(catalog.mods.filter(m=>m.published).map(m=>m.game))].map(g=>`<option>${esc(g)}</option>`).join('')}</select><select id="category" aria-label="Категория"><option value="">Все категории</option>${[...new Set(catalog.mods.filter(m=>m.published).map(m=>m.category))].map(c=>`<option>${esc(c)}</option>`).join('')}</select><select id="sort" aria-label="Сортировка"><option value="date">Сначала обновлённые</option><option value="name">По названию</option></select></div><div id="cards" class="grid"></div>`;const draw=()=>{const q=document.querySelector('#search').value.toLocaleLowerCase(),cat=document.querySelector('#category').value,game=document.querySelector('#game').value;const mods=catalog.mods.filter(m=>m.published&&(!game||m.game===game)&&(!cat||m.category===cat)&&(m.name+' '+m.summary).toLocaleLowerCase().includes(q)).sort((a,b)=>document.querySelector('#sort').value==='name'?a.name.localeCompare(b.name,'ru'):(latest(b)?.date??'').localeCompare(latest(a)?.date??''));document.querySelector('#cards').innerHTML=mods.map(m=>`<article class="card"><a class="card-content" href="#mod/${esc(m.id)}">${cover(m)}<div class="card-body"><span class="tag">${esc(m.game)} · ${esc(m.category)}</span><h2>${esc(m.name)}</h2><p>${esc(m.summary)}</p><div class="card-bottom"><span>${latest(m)?'v'+esc(latest(m).version):'<span class="demo">Пример карточки</span>'}</span><span class="muted">${latest(m)?date(latest(m).date):'Подробнее'}</span></div></div></a>${quickDownload(m)}</article>`).join('')||'<p class="empty">Ничего не найдено. Попробуйте другой запрос.</p>';};for(const id of ['search','game','category','sort'])document.getElementById(id).addEventListener('input',draw);draw();}
const links=v=>(v?.links??[]).map(l=>`<a class="btn" href="${esc(url(l.url))}" target="_blank" rel="noopener noreferrer">Скачать · ${esc(l.label)}</a>`).join('');
function richText(value){let out='',items=[];const inline=s=>esc(s).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');const flush=()=>{if(items.length){out+='<ul>'+items.map(s=>'<li>'+inline(s)+'</li>').join('')+'</ul>';items=[]}};for(const line of String(value??'').split(/\r?\n/).map(s=>s.trim())){if(!line)continue;const item=line.match(/^[-•]\s+(.+)$/);if(item){items.push(item[1]);continue}flush();out+=line.length<100&&(/:$/.test(line)||/^\*\*.+\*\*$/.test(line))?'<h3>'+inline(line.replace(/:$/,''))+'</h3>':'<p>'+inline(line)+'</p>'}flush();return out;}
function detail(id){const m=catalog.mods.find(m=>m.id===id&&m.published);if(!m){app.innerHTML='<h1>Мод не найден</h1><a href="#">Вернуться к каталогу</a>';return}const v=latest(m);app.innerHTML=`<a class="back" href="#">← Каталог модов</a><div class="mod-heading"><span class="tag">${esc(m.game)} · ${esc(m.category)}</span><h1 class="mod-title" title="${esc(m.name)}">${esc(m.name)}</h1><div class="mod-meta">${v?`<span>v${esc(v.version)}</span><span>Обновлено ${date(v.date)}</span>`:''}${m.credits?.length?`<span>Авторы: ${m.credits.map(esc).join(', ')}</span>`:''}</div></div><div class="detail modern-detail"><section class="mod-sections"><article class="box mod-description"><h2>О моде</h2>${m.demo?'<p class="notice">Пример карточки</p>':''}<div class="formatted-description">${richText(m.description)}</div></article>${m.screenshots.filter(url).length?`<article class="box mod-gallery"><h2>Скриншоты</h2><div class="gallery">${m.screenshots.filter(url).map(s=>`<a href="${esc(url(s))}" target="_blank" rel="noopener"><img src="${esc(url(s))}" alt="Скриншот ${esc(m.name)}" loading="lazy"></a>`).join('')}</div></article>`:''}<article class="box mod-history"><h2>История версий <span class="history-count">${m.versions.length}</span></h2>${m.versions.map((entry,i)=>`<details class="release"><summary><span>v${esc(entry.version)} ${i===0?'<em>Актуальная</em>':''}</span><small>${date(entry.date)}</small></summary><div class="release-body formatted-description">${richText(entry.changes)||'<p class="muted">Описание изменений не указано.</p>'}<div class="actions">${links(entry)}</div></div></details>`).join('')||'<p class="muted">Версий пока нет.</p>'}</article></section><aside class="box download-panel"><span class="tag">АКТУАЛЬНАЯ ВЕРСИЯ</span><h2>${v?'v'+esc(v.version):'Скоро здесь'}</h2><div class="actions">${links(v)}</div><div class="install-note"><h3>Установка</h3><p>Способ установки и требования — в описании мода. Игровые моды обычно помещаются в папку mods.</p></div>${m.sourceUrl?`<a class="source-link" href="${esc(url(m.sourceUrl))}" target="_blank" rel="noopener noreferrer">Страница на KingMods ↗</a>`:''}</aside></div>`;}
function updates(){const entries=catalog.mods.filter(m=>m.published).flatMap(m=>m.versions.map(v=>({m,v}))).sort((a,b)=>b.v.date.localeCompare(a.v.date));app.innerHTML='<span class="eyebrow">ЖУРНАЛ</span><h1>Обновления модов</h1>'+ (entries.map(({m,v})=>`<article class="version"><span class="tag">${date(v.date)}</span><h2><a href="#mod/${esc(m.id)}">${esc(m.name)} · ${esc(v.version)}</a></h2><p>${esc(v.changes)}</p></article>`).join('')||'<p class="empty">Здесь появятся новые версии модов.</p>');}

function renderGames(){app.innerHTML=`<div class="games-heading"><span class="eyebrow">BMPROD GAMES</span><h1>Мини-игры</h1><p class="muted">Небольшой перерыв между делами на ферме. Играй прямо в браузере — на телефоне или ПК.</p></div><div class="games-grid"><article class="box game-card"><a class="game-art" href="games/mini-farm.html" aria-label="Играть в Мини-ферму"><span>☀️</span><div>🏡 🌳</div><strong>🌾 🥕 🌽</strong></a><div class="game-description"><span class="tag">Ферма · Спокойная игра</span><h2>Мини-ферма</h2><p class="muted">Сажай, поливай и собирай урожай. Зарабатывай монеты и улучшай лейку. Играй в своём темпе, без ограничения времени.</p><p class="game-meta">Телефон и ПК · Без установки · Без сохранений</p><a class="btn" href="games/mini-farm.html">Играть</a></div></article></div>`;}
function route(){const h=location.hash;document.querySelector('.brand-banner').hidden=h.startsWith('#mod/')||h.startsWith('#games');document.querySelectorAll('[data-nav]').forEach(a=>a.setAttribute('aria-current',(h.startsWith('#games')&&a.dataset.nav==='games'||h==='#updates'&&a.dataset.nav==='updates'||(!h||h==='#')&&a.dataset.nav==='catalog')?'page':'false'));if(h==='#games')renderGames();else if(h==='#updates')updates();else if(h.startsWith('#mod/'))detail(h.slice(5));else renderCatalog();window.scrollTo(0,0);}
fetch('data/catalog.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('Не удалось загрузить каталог');return r.json()}).then(c=>{catalog=validate(c);document.querySelector('#catalog-count').textContent='Модов в каталоге: '+catalog.mods.filter(m=>m.published).length;route();window.addEventListener('hashchange',route)}).catch(e=>{app.innerHTML=`<h1>Каталог недоступен</h1><p>${esc(e.message)}</p><button class="btn" onclick="location.reload()">Повторить</button>`});

let copyNoticeTimer;
function copyNotice(message){
 let notice=document.getElementById('copy-notice');
 if(!notice){notice=document.createElement('div');notice.id='copy-notice';notice.className='copy-notice';notice.setAttribute('role','status');notice.setAttribute('aria-live','polite');document.body.append(notice)}
 clearTimeout(copyNoticeTimer);notice.textContent=message;notice.hidden=false;
 copyNoticeTimer=setTimeout(()=>{notice.hidden=true},3000);
}
async function copyDownloadUrl(value){
 if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(value);return}catch{}}
 const field=document.createElement('textarea');field.value=value;field.style.cssText='position:fixed;left:-9999px;top:0';field.setAttribute('readonly','');document.body.append(field);
 const focused=document.activeElement;let copied=false;
 try{field.select();field.setSelectionRange(0,field.value.length);copied=document.execCommand('copy')}finally{field.remove();focused?.focus({preventScroll:true})}
 if(!copied)throw Error('Copy failed');
}
app.addEventListener('click',async event=>{
 const button=event.target.closest('[data-copy-url]');if(!button)return;
 button.disabled=true;
 try{await copyDownloadUrl(button.dataset.copyUrl);copyNotice('Скопировано в буфер')}
 catch{copyNotice('Не удалось скопировать ссылку. Попробуйте ещё раз.')}
 finally{button.disabled=false}
});
